# Generated by Django 4.2.4 on 2023-08-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_remove_customuser_doctor_customuser_specialist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approved_appointments',
            field=models.ManyToManyField(blank=True, related_name='approved_doctors', to='usermanagement.appointment'),
        ),
    ]
