# Generated by Django 4.2.4 on 2023-08-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_appointment_prescription_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_availabilities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
